sudo: false

dist: trusty

services:
  - mongodb

language: go

os:
  - linux

go:
  - master

before_install:
  - go get -v ./...

before_script:
  - sleep 15

script:
  - go test -v ./...
deploy:
  provider: heroku
  api_key:
    secure: By2fOt1by3CnhSclmxhgtyh2fyXX4ZStzZS5Kv1C2TsqpdI3qmxtVKtsCakbC9U+T6flgaI5Opr7tPaeewZqQb7OU2MVF4J2f+PetNgZP657MAFSoQJEVpXPJPud3cLZ/1Fn3TRJLd90B/rPYUzROSaBJWRrTZ/n94NuVbeT77JePYhSmSM6EEPkBD/nt4gHRn6FXBH+e+sej7e3bX3MZdy6BFPLkeEBO7xox1D0qgk/hmuh1XhKfffb6796ry/gXf+yyjBL6xy/PCyZPjgeDU0QzGdl46YpWIQij0fXx+djy744kHrScxWIDgjcTRTCjt235vZC+XmHK9MAtNkNYX7L2MBcTUqLjbunaIQ+eEMyqUmAAugz23VOcTWiNZOGg94G4aZDC8Z9JIeqrtdCx54RmfMela8YFrU9+UgU5i/C9Zq4Jz43ZPwFz7KVh3UlT8CmO2K+J9JaiGIiscSCZbzu1gnse6mf4xrHc9bcMYs90XPe1hncrGs3gzRAwpwVUkmy5dqZlTKAm1feQZIJ3L6c43tCDJxR6twba5gqZjHQmHwdC8H/pv2sg83FHj/8oNSoWd3Yluv3H6IdCsglHNXZXY5rtt3HkSC6ThvRtAAFzlgpniclNT0AVAigTNyfRq0fCUJdpI8ACSmB38S8+VH3RvSejH+73qFOn554wJU=
