sudo: false

dist: trusty

services:
  - mongodb

addons:
  code_climate:
    repo_token:
       secure: "ucAP/59imd6gjYu+QhxTVPrOi+PCRBjxzZAlPXztnTrk8GyPjMtsXIoLSC5VrkaaDOwuOqg9Kh3JTTjh/dobnbF/NmGVvCqBFCWYjcrKXLEVplwJ8s73PZ5JQsFmKKRko6hxltIFtOHzwWk6nWt5CPuQitBFMoJfsjPdS98h3Ftnw0Cu9EpCv7q+rXDXNj3lDrOsygumeCWI1qYcIHLWYq4zPe1j3CVOeeRXZkfrs1VALpNA3D5JMxDY9TXSlGr3NKaE3R23AtZzvcof7W4AwFGJHyjh/x2c5pMZDCChW/kW6CoFdi8n1+zsi7Cjl9kZ6ZXEkKU4tlmWi55PjQxSsYVBLftjKlR3z9baXn6b8ATbvWWMZLGfY4nY5qlt73ec21S5aHc5TXv+1R3Olnq0iWTaZbbtoJm71whGVwdIyWpSLAQbi97/+B+YgPkQwJ2xgmZVRylxzft5NPzY38gENVumsmxw2c+Ezivg4yz5ws8rJpMWJwJ4DK8J2ooznI+ihT2hoMGaJrr3XS+SLb+FfPU8ifsZSc3YndvDlBrBxp9/OjUH98uRwrFDn/bghyeaPSs+Zjted+vWt31ZFqEeaw8vgUT3xmOIyshQ+u7nUAuBF8K9HfS/eZ+4r9UR8Wbk/cwQgTk2nNUvbMrFA4MJjCypWZOAtxmGl3OsBhH869U"

language: go

os:
  - linux

go:
  - master

before_install:
  - go get -v ./...

before_script:
  - sleep 15

script:
  - go test -v ./...

deploy:
  provider: heroku
  app: crud-go-mongodb
  api_key:
    secure: fsuqw7Ho39fdZQ6pDxknjl5/uPe/Ukgf+ZJzyJXXCM2HhQSQaYPuYJFNqXPfYykjKbS7DOY35oWvy/J3eg60l1r0LJZIbV58Ae2Y3CODPZKGBEnhQiYqNlTlxIjn7CDbxp7/Mz5t8sb7CFHQgWHioVxfUw9e0og3O3X0vbSkzJ8Dv5GnBv0kbNMk3dAw0N528KA/SDS1S+WYoaXwjaLOvQjtLBTa7qHnIZ+f3QQlJYqZVJgQgN/NHuxMBG2PCDZ3PdR3UuHJjwDQjiYeKhux2ZjGjRGwXecJlog5dbSqoEp665k3Pp4yB6Uld8KH2RKJryXc+RqlZ99a4kJ+lfEP+SAj/weOXelhL/vC5IAywODxbSEooOVHf6/R2yok6cAdaOvSHs73AcD+nscgcq6QFs0E9TUXz8hRPLWtRwY+bQLl8dLlc/AG8hH4ZZeRi/A9+x4IZjHOybMUOB1aDKkweEbnwOZx+DNYJ4is0F8/VpzEX5E6oLDYR2tPATg/XLv5UJU8+UFFeJwIqCwjEZLwQvbe5VcIbRMi/jcpJPkT/FIwYBo45DtDGmJFrg+dakZ+eo3ARcux62gyH4H+Gk8ladb2ge3h0xMv2ez6rc3MaInB+u8+xAynM6rRI02n1XeuKOQHNuSLxygue4IwPvXpelQIWBTL1NYHJntydnuGknw=
  strategy: git
  on:
    all_branches: true
